ALTER TABLE `user_master`
  ADD COLUMN `PasswordHash` VARCHAR(255) NULL AFTER `Email`;

ALTER TABLE `user_master`
  MODIFY COLUMN `IsActive` TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE `user_master`
  MODIFY COLUMN `CreatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `UpdatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
