CREATE TABLE IF NOT EXISTS order_master (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderNumber VARCHAR(50) NOT NULL UNIQUE,
  DealerId INT NOT NULL,
  DistributorId INT NOT NULL,
  SalesPersonId INT NOT NULL,
  CreatedByUserId INT NOT NULL,
  TotalAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
  Notes VARCHAR(255) NULL,
  AttachmentPath VARCHAR(255) NULL,
  OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Status ENUM('PENDING','APPROVED','REJECTED','FULFILLED') DEFAULT 'PENDING',
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (DealerId) REFERENCES user_master(Id),
  FOREIGN KEY (DistributorId) REFERENCES user_master(Id),
  FOREIGN KEY (SalesPersonId) REFERENCES user_master(Id),
  FOREIGN KEY (CreatedByUserId) REFERENCES user_master(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS order_items (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductId INT NOT NULL,
  Quantity DECIMAL(12,2) NOT NULL,
  UnitPrice DECIMAL(12,2) NOT NULL,
  TotalAmount DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (OrderId) REFERENCES order_master(Id) ON DELETE CASCADE,
  FOREIGN KEY (ProductId) REFERENCES product_master(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
