-- Create category master table
CREATE TABLE IF NOT EXISTS `category_master` (
  `Id` INT NOT NULL,
  `CategoryName` VARCHAR(80) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `CreatedOn` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedOn` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

