CREATE DATABASE IF NOT EXISTS rewarity_web_db;
USE rewarity_web_db;

CREATE TABLE IF NOT EXISTS user_master (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(100) NOT NULL,
  Email VARCHAR(100),
  Phone VARCHAR(20),
  PasswordHash VARCHAR(255),
  Role ENUM('SUPER_ADMIN','EMPLOYEE','DISTRIBUTOR','DEALER','SALESPERSON') DEFAULT 'DEALER',
  IsActive BOOLEAN DEFAULT TRUE,
  IsApproved BOOLEAN DEFAULT FALSE,
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_master (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NULL,
  UserTypeId INT NULL,
  Title VARCHAR(100) NOT NULL,
  Message TEXT NOT NULL,
  Screen VARCHAR(50) NULL,
  URL VARCHAR(255) NULL,
  IsRead BOOLEAN DEFAULT FALSE,
  IsActive BOOLEAN DEFAULT TRUE,
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(150) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  DisplayName VARCHAR(150) NOT NULL,
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO admin_users (Email, PasswordHash, DisplayName)
VALUES (
  'admin@rewarity.com',
  '$2y$12$Z9s7k3sflvmzKMiqg/JNZOicFfo18ThyIoZVGNmkPDOUSAG.TxqzG',
  'Super Admin'
)
ON DUPLICATE KEY UPDATE
  PasswordHash = VALUES(PasswordHash),
  DisplayName = VALUES(DisplayName),
  IsActive = 1;


CREATE TABLE IF NOT EXISTS order_master (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderNumber VARCHAR(50) NOT NULL UNIQUE,
  DealerId INT NOT NULL,
  DistributorId INT NOT NULL,
  SalesPersonId INT NOT NULL,
  CreatedByUserId INT NOT NULL,
  TotalAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
  Notes VARCHAR(255) NULL,
  AttachmentPath VARCHAR(255) NULL,
  OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Status ENUM('PENDING','APPROVED','REJECTED','FULFILLED') DEFAULT 'PENDING',
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductId INT NOT NULL,
  Quantity DECIMAL(12,2) NOT NULL,
  UnitPrice DECIMAL(12,2) NOT NULL,
  TotalAmount DECIMAL(12,2) NOT NULL
);
\nCREATE TABLE IF NOT EXISTS product_master (\n  Id INT NOT NULL,\n  ProductName VARCHAR(45) NOT NULL,\n  ProductCode VARCHAR(45) NOT NULL,\n  StartDate DATETIME DEFAULT NULL,\n  Description TEXT NULL,\n  IsActive BINARY(1) DEFAULT '1',\n  PurchasePrice DECIMAL(12,2) NOT NULL DEFAULT 0,\n  SellingPrice DECIMAL(12,2) NOT NULL DEFAULT 0,\n  CurrentStock DECIMAL(12,2) NOT NULL DEFAULT 0,\n  LowStockAlertLevel DECIMAL(12,2) DEFAULT NULL,\n  PRIMARY KEY (Id)\n);
